### ISSUE TITLE
Comparing using `<` and `>`

### ISSUE THREAD

**Issue by vikeri** [andrewmcveigh/cljs-time#123]
I have never seen any error when comparing things using `cljs.core/>` or `<` but I vaguely remember that one should use `before?` and `after?` instead. Why is this?

**Comment by andrewmcveigh** [comment]
If you are using `(require 'cljs-time.extend)`, then `<` and `>` should work just like `before?` and `after?`. Otherwise, you're relying on the underlying implementation of `goog.date` and javascript's `<` and `>` to provide ordering which may or may not be OK.
