### ISSUE TITLE
README cljs-time.coerce section refers to Java long

### ISSUE THREAD

**Issue by swannodette** [andrewmcveigh/cljs-time#20]
Seems to be due to copying over docs from clj-time. Nice library BTW.

**Comment by andrewmcveigh** [comment]
Thanks!

Yes, some of the lesser namespaces were copy-pasted before porting, I guess I've missed some of the Java/Joda references.

**Comment by swannodette** [comment]
If it emits Google Closure's Long instead now that would be nice to know!

**Comment by andrewmcveigh** [comment]
Looks like I'll be trawling the docs this week for mistakes & types!
