### ISSUE TITLE
Equality seems broken

### ISSUE THREAD

**Issue by mdhaney** [andrewmcveigh/cljs-time#22]
I've noticed that comparing 2 dates using = doesn't work as expected in most cases.  I understand there are mutable objects underneath, but even instance equality (I.e. comparing the same instance to itself) returns false, which just seems weird.  I dug through the source and found an implementation of = that does what I would expect, but of course that relies on explicitly calling that version of = and that doesn't work in a large number of cases.

I fixed this in my code by implementing IEquiv and everything works great now.  I was just curious why the library doesn't do that in the first place?  Was this a conscious design choice, and if so what drove the decision?

**Comment by mdhaney** [comment]
BTW, I would be happy to prepare a pull request with these changes if it was just an oversight or something.  My implementation of IEquiv simply delegates to your special = function.

**Comment by andrewmcveigh** [comment]
Hi, thanks for reporting.

I was already aware of this, and had done the extension of IEquiv, but I was advised to do this in an optionally loaded namespace, as goog.date is widely used, and extending = in this way could break things for other people.

I've been too busy recently to make the release, but I'll try to fit it in tomorrow.

**Comment by andrewmcveigh** [comment]
Fixed in `[com.andrewmcveigh/cljs-time "0.3.1"]`. Sorry it took so long to get the release out!

**Comment by puppybits** [comment]
This took me a while to figure out. I'm wondering if it would it be more practical to use a proxy or wrapper class for goog.date.*. That should allow the implementation of equality w/o breaking other people's things. It might also be a good setup to work on an immutable date data structure. 

I'd be happy to do the work and send a pull request. I LOVE this lib. Thanks for working on it.

**Comment by andrewmcveigh** [comment]
@puppybits  I've considered wrapping the `goog.date.*` stuff before to squeeze in better timezone support.

TBH, I'm not really sure if `cljs-time` should move further from `goog.date`. Personally I think I'd like it to, but if it does move further away, I'd consider ditching `goog.date` completely. I trialled a branch[1] without `goog.date`, but didn't feel confident it was the right direction.

[1] https://github.com/andrewmcveigh/cljs-time/tree/wip/keep-new-data-structure
