### ISSUE TITLE
TypeError: Cannot read property 'from_long' of undefined

### ISSUE THREAD

**Issue by jaredbowie** [andrewmcveigh/cljs-time#27]
I'm having trouble using the from-long function.  In fact nothing from coerce is working.
```clojure
(cljs-time.core/date-time 1986 10 14 22)
#<19861014T220000>
(cljs-time.coerce/from-long 893462400000)
#<TypeError: Cannot read property 'from_long' of undefined>
```

**Comment by andrewmcveigh** [comment]
"TypeError: Cannot read property 'from_long' of undefined"
Hi,

This is usually an indication that you haven't required the correct namespace in the namespace declaration (or elsewhere).

You'd need to require *both* `cljs-time.core`, and `cljs-time.coerce`, E.G.,

```clojure
(ns what.ever
  (:require
    [cljs-time.core :as time]
    [cljs-time.coerce]))
```

If you have done this, could you send me a small test-case that is failing?

**Comment by andrewmcveigh** [comment]
Any update on this. Do you still have the issue?

**Comment by andrewmcveigh** [comment]
Closing this as no feedback given. Please reopen if still an issue.
