### ISSUE TITLE
Compiler exception when adding to boot dependencies

### ISSUE THREAD

**Issue by nblumoe** [andrewmcveigh/cljs-time#28]
I get the following error after adding the cljs-time dependecy to build.boot:

    clojure.lang.Compiler$CompilerException: java.lang.IllegalArgumentException:
    No single method: _setup of interface: cljs.repl.IJavaScriptEnv found for function:
    -setup of protocol: IJavaScriptEnv, compiling:(cemerick/piggieback.clj:149:5)

    java.lang.IllegalArgumentException: No single method: _setup of interface:
    cljs.repl.IJavaScriptEnv found for function: -setup of protocol: IJavaScriptEnv

Full output is available here https://gist.github.com/nblumoe/b7667ce2072f0d811196

Is this a cljs-time issue?

**Comment by andrewmcveigh** [comment]
Hi,

As far as I've seen, this happens when there are conflicting versions of piggieback and clojurescript. I use the cemerick/austin plugin for development which brings in piggieback, but as it's a plugin I don't think it should be bleeding through to your project. Maybe this is a difference in how boot works?

Could you provide a sample boot project file that shows this issue?

**Comment by nblumoe** [comment]
Hi,

an example can be found here: https://github.com/nblumoe/cljs-time-test/blob/master/build.boot#L8

To reproduce the issue run `boot dev`. Just running `boot build` does not produce the error.
The issue only occurs when I require `reagent` before `cljs-time` the other way around it does not happen.

I know this is far from a minimal example. Let me know if I can be of any further help. Maybe the problem is obvious to you now already.

**Comment by andrewmcveigh** [comment]
Thanks.

I think that the problem probably is that the `clojurescript` version that `reagent` pulls in is conflicting with the version of `piggieback` that `cljs-time` pulls in via the `austin` plugin. I've not worked with `boot` yet, so I'm not really sure why `cljs-time`'s plugins are getting pulled through. I'll have a look to see if I can work out why that's happening.

As a workaround, you could try explicitly excluding `austin` & `piggieback`, if boot supports that.

**Comment by pangloss** [comment]
Hi Andrew,

Would it maybe make more sense to move plugins like austin, lein-auto-release, and marginalia into your ~/.lein/profiles.clj instead?

Regards,
Darrick

**Comment by andrewmcveigh** [comment]
Thanks Darrick, 

I've done that in c33f83ed37f6c7c769d2275ad9d883109d02a7ee, though it doesn't really answer the question of why `boot` pulls dev plugins in. I guess that's a question for `boot`'s authors.

Fixed in `[com.andrewmcveigh/cljs-time "0.3.4"]`.
