### ISSUE TITLE
formatter A broken

### ISSUE THREAD

**Issue by deadghost** [andrewmcveigh/cljs-time#30]
`0.3.4`
It goes from `5:00 PM` to `5:00 AM`.

    (def my-time (f/parse (f/formatter "h:mm A") "5:00 PM")) ; => #<00101T050000>
    (f/unparse (f/formatter "h:mm A") my-time) ; => "5:00 AM"

**Comment by deadghost** [comment]
It doesn't appear that `h` takes into consideration the value of the meridiem and will always return an AM hour value.

**Comment by andrewmcveigh** [comment]
Thanks for the report. Fixed in `0.3.5`
