### ISSUE TITLE
Support setting client clock skew

### ISSUE THREAD

**Issue by DomKM** [andrewmcveigh/cljs-time#31]
Often, clients have incorrect times and zones. For many applications, it is essential to deal with the server time; the client time is irrelevant.

It would be great if `now`, `today`, etc. could use custom time and zone settings instead of relying on the client's default settings. Would you be interested in a PR that adds this functionality?

**Comment by andrewmcveigh** [comment]
It would be great if cljs-time had better timezone support, it's one of my longer-term goals. It's not exactly straightforward though, as AFAIK neither JS nor google closure has much timezone support.

Do you have an implementation in mind?

**Comment by DomKM** [comment]
I wasn't aware of the poor timezone support in Google Closure. Ignoring that, setting the client clock skew is still extremely useful.

The solution to this is a dynamic `*client-skew*` var which holds the client skew in milliseconds and defaults to `0`. Whenever a new `Date`, `DateTime`, or `UtcDateTime` is created from the client's current time, add `*client-skew*` milliseconds to it before returning it.

Optionally, add a `set-client-time!` function which takes a server time, calculates the client skew in milliseconds, and sets `*client-skew*`.

Would that approach be of interest?

**Comment by andrewmcveigh** [comment]
Hi, sorry about the delay in coming back to you.

I'm not really keen on the implementation to be honest. It seems like a possible source of confusion, and is easily maintained in application code with a function such as 'adjust-for-client-skew or something. Then you've got the whole thing of calculating client skew over the network, which admittedly isn't that complicated, but certainly doesn't belong in `cljs-time`.

I'm not sure this feature really belongs in a library based around date/time parsing/manipulation. It's more client-server/transporty. If you don't really care about the time/zone the client has, why would you use it at all? Maybe I'm missing something? What's your use-case?

**Comment by DomKM** [comment]
No worries and thanks for your time. I appreciate your consideration of this issue.

In `clj-time` (or any server-side time library), you can change the current time by changing the computer's time. JavaScript does not have an API for changing the computer's time nor does it allow one to change the time to something different than the computer's time.

Here's an example of why this feature is necessary in any temporal application:
* The server is sending items to the client on which the user may bid. The client allows the user to bid on items until they expire.
* The server time is `2015-05-20T00:00:00Z`.
* The client time is  `2015-05-20T00:05:00Z`.
* Item X has an expiration time of `2015-05-20T00:10:00Z`.

In this scenario, the client will think item X expired 5 minutes before it actually did. However, if the client knows that it is 5 minutes ahead of the server, it can compensate by subtracting 5 minutes every time it creates a datetime based on the current time.

If client skew cannot be set within `cljs-time`, the only way to compensate for incorrect clients is to never call `now`, `today`, or any other function that creates a current datetime directly. Instead, every one of these functions need to be wrapped to take the client skew into account and everyone on the team needs to know to never use `cljs-time.core/now`, even though it may appear to work correctly on their development machine.

Essentially, I am asking for a way to set the current time of the client. All we need is a way to tell `cljs-time` that "the current time is 5 minutes slow." Without this, using core functionality of `cljs-time` is not an option for us.

**Comment by andrewmcveigh** [comment]
Hi,

OK, I had overlooked this type of use.

Phrased as "I want to set the system-time" doesn't sound like an unreasonable request (disregarding the fact that it's impossible in the browser). I guess the term "clock-skew" threw me off.

Looking at the joda-time implementation[1], I think something similar can be done for cljs-time, it's not too dissimilar from your suggested implementation. Cljs-time does already allow users to set a static system-time, but that's not quite what you're after.

Just FYI (if you didn't know): you can already do this kind of thing if you're willing to bend clojurescript/cljs-time a bit.
```clojure
(set! cljs-time.core/now
  (fn []
    (cljs-time.core/plus (goog.date.UtcDateTime.)
                         (cljs-time.core/millis offset-in-ms))))
```
[1] https://github.com/JodaOrg/joda-time/blob/master/src/main/java/org/joda/time/DateTimeUtils.java#L109

**Comment by DomKM** [comment]
Excellent! I'm very happy to hear that this is within scope and sorry for the confusion.

I wasn't aware of the Joda Time implementation. You're right, it's very similar to what I was proposing.

Where do we go from here? Would you like a PR with this functionality?

**Comment by andrewmcveigh** [comment]
Hi,
I'd happily accept a PR that's similar in spirit to the Joda implementation. It seems that `now`, `today`, etc., could defer to a dynamically assignable `ms-provider` function to get the "current-time". If you're happy to do that, by all means :+1:
