### ISSUE TITLE
goog.date.duration

### ISSUE THREAD

**Issue by shaunlebron** [andrewmcveigh/cljs-time#36]
just FYI, someone inquired on #clojurescript clojurians slack:

> Does anyone have a "time remaining" function lying around that humanises seconds to "5 days", "4 hours", "32 minutes"? Would save me some time.

Looks like [goog.date.duration](http://google.github.io/closure-library/api/namespace_goog_date_duration.html) does this and might be nice to include in cljs-time.

**Comment by andrewmcveigh** [comment]
Cheers, I saw that and was going to create an issue myself :+1:

**Comment by shaunlebron** [comment]
awesome,thanks!
