### ISSUE TITLE
(instant-map) function has negative days

### ISSUE THREAD

**Issue by webrage** [andrewmcveigh/cljs-time#38]
Hi,

clj-time "0.10.0"

When passing an interval that spans across more than a year to the function (instant->map) the :day field of the map has a negative  number.  It works in clj.time

I believe if the end date passed to the deftest function (in format_test) was changed from '1986' to '1987' it will show this error?

Thanks

**Comment by andrewmcveigh** [comment]
Fixed in release `0.3.11`
