### ISSUE TITLE
time-format/date-parsers returns nil on iPhone 4

### ISSUE THREAD

**Issue by andrewmcveigh** [andrewmcveigh/cljs-time#40]
@Jell:
I'm asking because I've been tracking down a bug I found on iPhone 4 that I've been pulling my hair on for 2 days straight, and I don't know the exact details of why but this:

```clojure
(time-format/date-parsers "yyyy")
```

Returns nil if and only if I run it on an iphone 4 without using the debugger. If I use the debugger it works again.

So I have no idea why, but if I wrap date-parsers in a (defn) the problem goes away. I suspect it has something to do with the naked top level let, as mentioned in this issue. Do you mind if I provide a PR where I wrap all the top level hashes in a defn?

**Comment by andrewmcveigh** [comment]
@Jell:


Ah sorry I should be a bit more precise. The issue only happens on iphone 4 with iOS 7, it works on iphone 4S. I am not calling date-parsers directly, that's just the source of the bug.

By debugger I mean the safari debugger that allows you to inspect a webpage loaded in the iphone. It's not even a debugger per se, just a web inspector (the only web inspector you have access to when using an iphone).

I'm using the following compilation settings:

{:optimizations :whitespace
 :pretty-print true
 :static-fns true}

But got the same results using advanced compilation. After looking into it, I could narrow down the error to a much smaller failing case:

(def date-parsers
  (let [d :d
        M :M
        y :y
        a :a
        m :m
        s :s
        S :S
        h :h
        H :h]
    {"d" d
     "dd" d
     "D" d
     "DD" d
     "DDD" d
     "dth" d
     "M" M
     "MM" M
     "y" y
     "yy" y
     "yyyy" y
     "Y" y
     "YY" y
     "YYYY" y
     "a" a
     "A" a
     "m" m
     "s" s
     "S" S
     "h" h
     "H" H
     "hh" h}))

(set! (.-onload js/window) (js/alert (date-parsers "yyyy")))

This shows an alert with nil when running without the webinspector, and :y when using the webinspector. My conclusion is that it's not a bug in your lib, but something lower level (probably even a bug in the JS interpreter of the iPhone), but I can circumvent it by not having that top level data structure.

I suspect it has something to do with having some top-level binding that's somehow breaking things. I'll investigate some more and report here and to the ClojureScript devs.

**Comment by Jell** [comment]
OK didn't get time to work on that but my colleague found this which means I'm not going crazy at least!

https://github.com/facebook/immutable-js/issues/92

Very similar to what I'm observing (work with the inspector but not without, and only for iphone 4 specifically). Not sure why replacing the `(def x {})` with `(defn x [key] ({} key))` solves it and the exactly what the conditions are to trigger it yet though.

**Comment by Jell** [comment]
So yeah, I finally succeeded in have a minimal failing spec!

https://github.com/Jell/iphone-bug

So that's the good news! :) I'll report this upstream to the ClojureScript devs.

**Comment by Jell** [comment]
Reported here: http://dev.clojure.org/jira/browse/CLJS-1380

**Comment by andrewmcveigh** [comment]
So, I guess this not a cljs-time bug, and from the sounds of it, it's not a ClojureScript bug either.

Thanks for reporting upstream.

I'm not sure what to do about this long-term. I guess that the next major release will solve this, as the code should no-longer contain top-level maps.

I'll close this issue, if you feel like it should still be open or you have any suggestions, please let me know.

**Comment by Jell** [comment]
Correct! TL;DR: The JIT compiler on iphone 4 is broken and does some buggy inlining of bit-wise operations, which affects hashing. The solution was to disable the JIT compiler for some of the bit-wise operations by wrapping them in a try/catch block.
