### ISSUE TITLE
Formatter escape character not working

### ISSUE THREAD

**Issue by Guthur** [andrewmcveigh/cljs-time#44]
It appears that the escape character ' is not properly escaping the enclosed string when doing unparse.

(cljs-time.format/unparse (cljs-time.format/formatter "'Yesterday:' MMMM dd") (cljs-time.core/yesterday)) => "Y348t3r2amy: September 02"

cljs-time = 0.3.12
cljs = 1.7.58

**Comment by andrewmcveigh** [comment]
Fixed in `0.3.14`
