### ISSUE TITLE
Tests are failing, but the build is passing

### ISSUE THREAD

**Issue by danielcompton** [andrewmcveigh/cljs-time#46]
The Travis CI status of this library says that it is passing, but the [build log](https://travis-ci.org/andrewmcveigh/cljs-time/jobs/79089697) shows that some tests actually failed.

**Comment by danielcompton** [comment]
It looks like the exit codes aren't being reported. One option is using doo, but I'm sure there must be other options too?

**Comment by andrewmcveigh** [comment]
Hmm... weird. Don't think it does this on my machine. I'll look into it, cheers!

**Comment by danielcompton** [comment]
The tests also fail on my machine when I run them, although they exit successfully.

**Comment by andrewmcveigh** [comment]
Looks like this happened either when I switched to cljs.test, or to using node as the test runner. Looks to be fixed now.

Thanks for noticing!
