### ISSUE TITLE
handle nils same way as clj-time

### ISSUE THREAD

**Issue by yogthos** [andrewmcveigh/cljs-time#49]
Some of the functions in cljs-time will NPE while the equivalent clj-time functions will handle nils intelligently. For example, [from-date](https://github.com/clj-time/clj-time/blob/d50b3ae3245ec518ad4d89efa13fc77a09d65f7e/src/clj_time/coerce.clj#L39) in clj-time does a `when` check on the date. I think this is very valuable as it allows you to safely chain the functions without having to pepper nil checks in-between.

**Comment by andrewmcveigh** [comment]
Thanks for the report, should be fixed in `0.3.14`

**Comment by yogthos** [comment]
:+1:
