### ISSUE TITLE
Week number in year is wrong

### ISSUE THREAD

**Issue by featalion** [andrewmcveigh/cljs-time#51]
Hi, I found an issue with formatters, like `:weekyear-week`. It spreads across all formatters, that uses `ww` (week number). Current implementation does not follow [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Week_dates).

It is actually very easy to fix the issue, because Google Closure library is already implement required method. Just change [this line](https://github.com/andrewmcveigh/cljs-time/blob/master/src/cljs_time/format.cljs#L158) to:

```clojure
  "ww" #(.getWeekNumber %)
```

**Comment by andrewmcveigh** [comment]
Hi,

So I've fixed the `"ww"` formatter as you suggest, but I've discovered that even that implementation is not correct.

Getting round to fixing `"xxxx"` & `"ww"` as per https://en.wikipedia.org/wiki/ISO_8601#Week_dates

Thanks for reporting!

**Comment by featalion** [comment]
This function seems to work fine for me:

```clojure
(defn week-of-year
  [date & {:keys [cut-off-day first-week-day] :or {cut-off-day 3, first-week-day 0}}]
  (goog/date.getWeekNumber (.getFullYear date)
                           (.getMonth date)
                           (.getDate date)
                           cut-off-day
                           first-week-day))
```

[Closure library API documentation on Date](https://closure-library.googlecode.com/git-history/docs/namespace_goog_date.html)

**Comment by pepijn** [comment]
https://closure-library.googlecode.com/git-history/docs/local_closure_goog_i18n_datetimeformat.js.source.html:
```
 * Symbol Meaning Presentation        Example
 * ------   -------                 ------------        -------
 * G        era designator          (Text)              AD
 * y#       year                    (Number)            1996
 * Y*       year (week of year)     (Number)            1997
 * u*       extended year           (Number)            4601
[...]

 * Item marked with '*' are not supported yet.
```

Does the statement above make clear that week years (`Y*`) are not supported in the Google Closure library at all? Can't have a proper week number without a week year, right?

**Comment by andrewmcveigh** [comment]
I have  a function for week/weekyear in a branch, seems to work but not extensively tested yet.

https://github.com/andrewmcveigh/cljs-time/blob/wip/real-parser/src/cljs_time/internal/unparse.cljs#L87

**Comment by andrewmcveigh** [comment]
This should have been fixed in `[com.andrewmcveigh/cljs-time "0.5.0-alpha1"]`, closing.

https://github.com/andrewmcveigh/cljs-time/blob/master/src/cljs_time/internal/unparse.cljs#L87
