### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Date' of undefined -> goog.date.Date in coerce.cljs

### ISSUE THREAD

**Issue by sergium** [andrewmcveigh/cljs-time#52]
trying to use version:   "0.3.14"

getting following error in the js-console:

>Uncaught TypeError: Cannot read property 'Date' of undefined
>(anonymous function) @ coerce.cljs:94

```clojure
  goog.date.Date
  (to-date-time [local-date]
    (when local-date (doto (goog.date.UtcDateTime.) (.set local-date))))
```

**Comment by andrewmcveigh** [comment]
Hey,

Any chance you're using `lein-figwheel <= 0.4.0`?

Could you perhaps give me a code snippet of what you're trying to call that's failing?

**Comment by sergium** [comment]
Hi,

I'm using [lein-figwheel "0.4.1"]

Here the only function I'm using:

```clojure

 (:require [clojure.walk     :as walk]            
            [cljs-time.core   :as time-core]
            [cljs-time.coerce :as time-coerce]
            [cljs-time.format :as time-format])


(defn timestamp->str [timestamp]
  (time-format/unparse (time-format/formatter "yyyy-MM-dd HH:mm:ss")
                       (-> timestamp
                         (/ 1000)
                         (time-coerce/from-long))))

```

**Comment by sergium** [comment]
Follow up.

Actually for me lib works well, I'm getting this error ONCE on first loading - I'm not using  goog.date.Date)

**Comment by andrewmcveigh** [comment]
So, I've not seen this before. I've seen similar things with `lein-figwheel`, so let me investigate a bit. I'll try to reproduce.

**Comment by sergium** [comment]
Ok, sure.

And thanks for rapid response!

If you need any help - just let me know.

**Comment by andrewmcveigh** [comment]
If you could provide (as much as possible) of your `project.clj` that would be great!

**Comment by sergium** [comment]
Ok, I'll create min-example project.

**Comment by sergium** [comment]
weird...

can't reproduce it in the clean project - looks like I've messed up with figwheel's config in my dev\prod setup

sorry for the mess - I think we can close issue 

when(if) I reproduce it - I will open new issue with the link to a git project where you can get the complete environment

**Comment by andrewmcveigh** [comment]
Closing this. If you still have the issue/can reproduce, please re-open.
