### ISSUE TITLE
with-locale

### ISSUE THREAD

**Issue by humanitiesNerd** [andrewmcveigh/cljs-time#62]
According to the documentation, in order to print datetimes according to a locale, "with-locale" should be used

The thing is I can't find with-locale in the code. Is it there ?

**Comment by andrewmcveigh** [comment]
Hi,

Sorry, there is no `with-locale` as there's not really much locale support in `goog.date` or plain js. The docs are wrong in this case.

**Comment by humanitiesNerd** [comment]
@andrewmcveigh ok, thanks anyway
