### ISSUE TITLE
Any plans to allow setters in date-times?

### ISSUE THREAD

**Issue by levitanong** [andrewmcveigh/cljs-time#72]
For example, given a certain date-time, I'd like to set the month.
```clj
(def dt (date-time 2016 9 13))
...
(def new-dt (set-month dt 4))
```

This is useful for charting and other edge cases, as it's cumbersome to have to create a new `date-time`, accessing the untouched fields of the base date-time, when all you want to change is one field.

```clj
(def dt (date-time 2016 9 13))
...
(def new-dt 
  (date-time
      (year dt)
      4
      (day dt)))
```

**Comment by danielcompton** [comment]
Two options are to use `plus` with a period `n` months to do this, or write a function to encapsulate what you are doing to create `new-dt`. 

I would argue against mutating dates, as that is historically a massive source of pain (Joda-Time and Java 8's Time libraries are both immutable, in reaction to the pain of Java Date's being mutable), and doesn't fit well with Clojure's preference for immutable data structures. AFAICT It also isn't present in clj-time, which this libraries API is based on.

**Comment by levitanong** [comment]
Ah, sorry, I did not communicate properly. I'm not asking for mutability at all—`set-month` would create a new date-time.

**Comment by andrewmcveigh** [comment]
Oh, just seeing the rest of your response right now...

I guess that I see your point somewhat, though I don't want to stray from the `clj-time` API. This library is purposefully a (as good as possible in js) mirror of the `clj-time` API, which in turn is based on the Joda-Time API.
