### ISSUE TITLE
API docs for the stable version (0.4.0)?

### ISSUE THREAD

**Issue by eyelidlessness** [andrewmcveigh/cljs-time#75]
The repo's README links to API docs apparently generated for 0.5.0, which is marked as unstable. Switching to the 0.4.0 tag has an API docs link which returns a 404. Is it possible to make both available?

**Comment by andrewmcveigh** [comment]
I've regenerated all versions of documentation, though 0.5.0/0.4.0 are very similar.

http://andrewmcveigh.github.io/cljs-time/0.4.0/index.html
