### ISSUE TITLE
Generated API docs for format/formatters is unreadable

### ISSUE THREAD

**Issue by timgilbert** [andrewmcveigh/cljs-time#79]
Hey, looking here:

http://andrewmcveigh.github.io/cljs-time/api/cljs-time.format.html#var-formatters

...it looks like some of the escaping is a little out of whack. It might be good to just provide a direct link to the source code from the README:

https://github.com/andrewmcveigh/cljs-time/blob/master/src/cljs_time/format.cljs#L58

**Comment by andrewmcveigh** [comment]
Hey, thanks for reporting. I've been fiddling around with documentation generation, but it's a little messed up.

I'll use a different library.

**Comment by andrewmcveigh** [comment]
Fixed as of ba44123
http://andrewmcveigh.github.io/cljs-time/latest/index.html
