### ISSUE TITLE
Is node.js supported?

### ISSUE THREAD

**Issue by madvas** [andrewmcveigh/cljs-time#88]
Is this lib supposed to be working with node.js? Since whichever function I try to call, when running on node.js a get error: 

```
#object[TypeError TypeError: Cannot read property 'call' of undefined]
```

**Comment by andrewmcveigh** [comment]
Yes, the library is tested using node.js, so it should work.

Could you share some context about what you're doing?

- Which version are you using?
- How are you using the library?
- Do you have a `project.clj` file?
- What does it look like?
- Are you using a REPL?
- Which one?

**Comment by madvas** [comment]
I resolved this by explicitly requiring `[goog.date.Date]` in namespace
