### ISSUE TITLE
cljs-time breaks with latest CLJS builds?

### ISSUE THREAD

**Issue by deg** [andrewmcveigh/cljs-time#89]
My project, using cljs-time, generates warnings with the latest ClojureScript builds when doing a `lein uberjar`. The warnings suggest that the problem lies in cljs-time, probably in the namespace definition of `cljs-time.core`.

I see the problem in all of 0.5.0-SNAPSHOT, 0.5.0-alpha2, and 0.4.0.

They compile fine in CLJS 1.9.456 or earlier; give some warnings in 1.9.493, and worse warnings in 1.9.495.

In 1.9.493:

> WARNING: No such namespace: cljs-time, could not locate cljs_time.cljs, cljs_time.cljc, or Closure namespace "" at line 567 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: Use of undeclared Var cljs-time/core at line 567 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: No such namespace: cljs-time, could not locate cljs_time.cljs, cljs_time.cljc, or Closure namespace "" at line 568 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: Use of undeclared Var cljs-time/core at line 568 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: No such namespace: cljs-time, could not locate cljs_time.cljs, cljs_time.cljc, or Closure namespace "" at line 569 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: Use of undeclared Var cljs-time/core at line 569 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: No such namespace: cljs-time, could not locate cljs_time.cljs, cljs_time.cljc, or Closure namespace "" at line 570 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: Use of undeclared Var cljs-time/core at line 570 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: No such namespace: cljs-time, could not locate cljs_time.cljs, cljs_time.cljc, or Closure namespace "" at line 571 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: Use of undeclared Var cljs-time/core at line 571 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: No such namespace: cljs-time, could not locate cljs_time.cljs, cljs_time.cljc, or Closure namespace "" at line 592 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: Use of undeclared Var cljs-time/core at line 592 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: No such namespace: cljs-time, could not locate cljs_time.cljs, cljs_time.cljc, or Closure namespace "" at line 593 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: Use of undeclared Var cljs-time/core at line 593 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: No such namespace: cljs-time, could not locate cljs_time.cljs, cljs_time.cljc, or Closure namespace "" at line 594 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: Use of undeclared Var cljs-time/core at line 594 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: No such namespace: cljs-time, could not locate cljs_time.cljs, cljs_time.cljc, or Closure namespace "" at line 595 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: Use of undeclared Var cljs-time/core at line 595 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: No such namespace: cljs-time, could not locate cljs_time.cljs, cljs_time.cljc, or Closure namespace "" at line 596 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: Use of undeclared Var cljs-time/core at line 596 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/core.cljs
WARNING: No such namespace: cljs-time, could not locate cljs_time.cljs, cljs_time.cljc, or Closure namespace "" at line 528 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/format.cljs
WARNING: Use of undeclared Var cljs-time/core at line 528 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/format.cljs
WARNING: No such namespace: cljs-time, could not locate cljs_time.cljs, cljs_time.cljc, or Closure namespace "" at line 532 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/format.cljs
WARNING: Use of undeclared Var cljs-time/core at line 532 /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs_time/format.cljs

in 1.9.195, I also see the following, though I don't know if it is related to cljs-time:

> Mar 09, 2017 1:23:35 PM com.google.javascript.jscomp.LoggerErrorManager println
> SEVERE: /home/deg/Documents/git/vuAgain/photovu/target/uberjar/cljsbuild-compiler-0/cljs/core/async.js:1426: ERROR - Parse error. No newline allowed before '=>'
> var inst_20540 = async(inst_20539);
>

**Comment by borkdude** [comment]
When can we expect a released version of this?

**Comment by borkdude** [comment]
I tried with the latest from master and ClojureScript 1.9.542. Still the same errors.

**Comment by Jarzka** [comment]
Same problem here. Why is this issue closed?

**Comment by borkdude** [comment]
Check the reactions in this issue: 
https://github.com/andrewmcveigh/cljs-time/issues/96
