### ISSUE TITLE
Modifiers of Datetime

### ISSUE THREAD

**Issue by LukasRychtecky** [andrewmcveigh/cljs-time#97]
Hi,

thanks for creating this library! I really like it.

What you think about extending `DateTimeProtocol` with `set-hours`, `set-minutes`, `set-seconds` and `set-milliseconds`? I use them in my project, thus I can create a PR if you want.

**Comment by danielcompton** [comment]
Dupe of #72.

**Comment by andrewmcveigh** [comment]
Thanks @danielcompton 

Yep, as I mentioned in #72 

> I don't want to stray from the clj-time API. This library is purposefully a (as good as possible in js) mirror of the clj-time API, which in turn is based on the Joda-Time API.
